import type { Metadata } from "next";

import { PageShell } from "@/components/marketing/page-shell";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `How ${siteConfig.name} collects, uses, and protects your personal information.`,
};

export default function PrivacyPolicyPage() {
  return (
    <PageShell title="Privacy Policy" subtitle="Last updated: January 2026">
      <h2>1. Information We Collect</h2>
      <p>
        We collect information you provide directly (name, email, phone, shipping addresses,
        payment details processed by our payment partners), information generated by your use of
        the platform (orders, wishlist, browsing activity, device and log data), and information
        from third parties (OAuth providers like Google or GitHub, when you choose to sign in with
        them).
      </p>

      <h2>2. How We Use Your Information</h2>
      <ul>
        <li>To process and fulfil orders, including shipping, invoicing, and returns.</li>
        <li>To personalize product recommendations and search results.</li>
        <li>To send transactional emails (order confirmations, shipping updates, OTPs) and, with your consent, marketing communications.</li>
        <li>To detect and prevent fraud, abuse, and security incidents.</li>
        <li>To comply with legal and tax obligations, including GST invoicing.</li>
      </ul>

      <h2>3. Sharing of Information</h2>
      <p>
        We share information with sellers fulfilling your orders, payment processors (Razorpay,
        Stripe) to complete transactions, logistics partners for delivery, and service providers
        (e.g. Cloudinary for media, Resend for email) strictly to operate the platform. We do not
        sell your personal information.
      </p>

      <h2>4. Cookies</h2>
      <p>
        We use essential cookies for authentication and cart persistence, and analytics cookies
        (Google Analytics, Microsoft Clarity) to understand how the site is used. You can control
        cookies through your browser settings.
      </p>

      <h2>5. Data Security</h2>
      <p>
        Your data is encrypted in transit (TLS) and at rest. Access to production data is limited
        to authorized personnel, and all tables enforce Row Level Security so users can only
        access their own records.
      </p>

      <h2>6. Your Rights</h2>
      <p>
        You can access, update, or delete your personal information from your Account settings at
        any time, or by contacting{" "}
        <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a>. You may also
        opt out of marketing emails at any time.
      </p>

      <h2>7. Changes to This Policy</h2>
      <p>
        We may update this policy from time to time. Material changes will be notified via email
        or a prominent notice on the platform.
      </p>
    </PageShell>
  );
}
